version: "3"

services:
    node-app:
        build: 
            context: .
            dockerfile: Dockerfile
        image: node-app-image
        container_name: node-app
        working_dir: /var/www/node
        restart: unless-stopped
        tty: yes
        ports:
            - "3000:3000"
        volumes:
            - ./:/var/www/node/
